const fs = require('fs');
const os = require('os');
const path = require('path');
const shortcuts = require('./shortcuts');

const COMPLETION_DATA_TYPES = ['options', 'shortcuts'];

module.exports = {
	bashScript,
	data,
	installBash,
};

function data(type, program) {
	switch (type) {
		case 'options':
			return optionNames(program);
		case 'shortcuts':
			return shortcutNames();
		default:
			return null;
	}
}

function installBash(options = {}) {
	const dir = options.dir || completionDir();
	const commandPath = options.commandPath || process.argv[1] || 'passgen';
	const names = normalizeNames(options.names);
	const script = bashScript(commandPath, names);
	const paths = completionFileNames(commandPath, names)
		.map(name => path.join(dir, name));

	fs.mkdirSync(dir, { recursive:true });
	paths.forEach(file => fs.writeFileSync(file, script, 'utf8'));

	return { path:paths[0], paths, names };
}

function bashScript(commandPath = 'passgen', names = []) {
	const command = commandPath === 'passgen' ? commandPath : path.resolve(commandPath);
	const targets = completionTargets(command, names)
		.map(shellQuote)
		.join(' ');

	return `# bash completion for passgen
# Generated by passgen --install-completions. Re-run that command to update.

__passgen_completion_command=${shellQuote(command)}

_passgen_completion() {
	local cur prev values

	COMPREPLY=()
	cur="\${COMP_WORDS[COMP_CWORD]}"
	prev="\${COMP_WORDS[COMP_CWORD-1]}"

	case "$prev" in
		-t|--type)
			values="$("$__passgen_completion_command" --completion-data shortcuts 2>/dev/null)"
			COMPREPLY=( $(compgen -W "$values" -- "$cur") )
			return 0
			;;
		--completion-data)
			COMPREPLY=( $(compgen -W "${COMPLETION_DATA_TYPES.join(' ')}" -- "$cur") )
			return 0
			;;
		-l|--length|-c|--count|-p|--prefix|-pp|--postfix|--language|--format|--completion-name)
			return 0
			;;
	esac

	if [[ "$cur" == -* ]]; then
		values="$("$__passgen_completion_command" --completion-data options 2>/dev/null)"
		COMPREPLY=( $(compgen -W "$values" -- "$cur") )
	fi
}

complete -F _passgen_completion ${targets}
`;
}

function optionNames(program) {
	const names = [];

	program.options
		.filter(option => !option.hidden)
		.forEach(option => {
			if (option.short) names.push(option.short);
			if (option.long) names.push(option.long);
		});

	return names;
}

function shortcutNames() {
	return shortcuts.all.reduce((names, shortcut) => {
		names.push(shortcut.name);

		return names.concat(shortcut.aliases || []);
	}, []);
}

function completionDir() {
	const root = process.env.BASH_COMPLETION_USER_DIR
		|| path.join(os.homedir(), '.local', 'share', 'bash-completion');

	return path.join(root, 'completions');
}

function completionTargets(command, names = []) {
	const basename = path.basename(command);

	return unique([
		'passgen',
		basename,
		`./${basename}`,
		command,
		...normalizeNames(names),
	]);
}

function completionFileNames(commandPath, names = []) {
	return unique([
		'passgen',
		path.basename(commandPath || 'passgen'),
		...normalizeNames(names),
	]);
}

function normalizeNames(names = []) {
	if (!Array.isArray(names))
		names = [names];

	return unique(names
		.flatMap(name => `${name}`.split(','))
		.map(name => name.trim())
		.filter(Boolean)
		.map(validateName));
}

function validateName(name) {
	if (/^[A-Za-z0-9_.-]+$/.test(name)) return name;

	throw new Error(`Invalid completion name '${name}'. Use a simple command or alias name without slashes.`);
}

function unique(items) {
	return items.filter((item, index) => item && items.indexOf(item) === index);
}

function shellQuote(value) {
	return `'${`${value}`.replace(/'/g, `'\\''`)}'`;
}
